version: "3.0"
volumes:
  mds_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/db/data
  auth_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/db/auth_data
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mds-db:
    container_name: mds-db
    image: postgres:15
    volumes:
      - mds_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mdsportal
      POSTGRES_USER: mdsadmin # change for production value 
      POSTGRES_PASSWORD: mdsadmin # change for production value 
    networks:
      - mds-network
    ports:
      - 5432:5432
  auth-db:
    container_name: auth-db
    image: postgres:15
    volumes:
      - auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak # change for production value
      POSTGRES_PASSWORD: keycloak # change for production value
    networks:
      - mds-network
  keycloak:
    container_name: mds-auth
    build:
      context: ./keycloak
    restart: on-failure
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: auth-db
      DB_PORT: 5432
      DB_DATABASE: keycloak # should be the same with POSTGRES_DB on auth-db container
      DB_USER: keycloak # should be the same with POSTGRES_USER on auth-db container
      DB_PASSWORD: keycloak # should be the same with POSTGRES_PASSWORD on auth-db container
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://mds.intranet/auth
      KEYCLOAK_USER: keycloak # change for production value
      KEYCLOAK_PASSWORD: keycloak # change for production value
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    volumes:
      - ./realm-export.json:/realm-export.json
      - ./themes/keycloak/login:/opt/jboss/keycloak/themes/keycloak/login
    depends_on:
      - auth-db
    networks:
      - mds-network
    # ports:
    #   - 8080:8080
  mds-api:
    container_name: mds-api
    image: ghcr.io/drupi0/mds-api:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mds-db:5432/mdsportal
      SPRING_DATASOURCE_USERNAME: mdsadmin # should be the same with POSTGRES_USER on mds-db container
      SPRING_DATASOURCE_PASSWORD: mdsadmin # should be the same with POSTGRES_PASSWORD on mds-db container
      KEYCLOAK_REALM: "http://mds.intranet/auth/realms/mds-auth"
      KEYCLOAK_ALLOWED_ORIGINS: ""
      ENCRYPTION_SEED: "my-secret-seed" # change for production value
    depends_on:
      - mds-db
      - keycloak
    networks:
      - mds-network
  mds-ui:
    container_name: mds-ui
    hostname: mds.intranet
    image: ghcr.io/drupi0/mds-ui:latest
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - mds-api
    networks:
      - mds-network
    volumes:
      - ./environment.json:/usr/share/nginx/html/assets/environment.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  mds-network:
    driver: bridge